In [1]:
import numpy as np
from math import *
import matplotlib.pyplot as plt





In [2]:
n_events=2#no. of events
n_rec=3#no. of receivers
rec_pos=np.zeros(shape=(n_rec,2))#2D list of rec positions, rec_pos[n]=[x,y] for n-1th rec
t_rec=np.zeros(shape=(n_rec,n_events))#2D list: stores sensor recordings in the format:
#[[events as recorded by rec1], [events as recorded by rec2],...] 
c=1

In [3]:
rec_pos[0]=(0,0)
rec_pos[1]=(1,0)
rec_pos[2]=(2,0)
t_rec[0,0]=1
t_rec[0,1]=4
t_rec[1,0]=2
t_rec[1,1]=1
t_rec[2,0]=2
t_rec[2,1]=3
print(t_rec)
t_noise=np.random.normal(loc=0.0,scale=0.02,size=(n_rec,n_events))
t_rec+=t_noise
print(t_rec)

[[1. 4.]
 [2. 1.]
 [2. 3.]]
[[1.0050765  4.01391777]
 [1.9803987  0.98726843]
 [2.0059358  3.00311738]]


In [4]:
def arrange_events(e):
    e=e-1
    '''returns array of time recorded in all sensors corresponding to e_th event w.r.t 0_th receiver'''
    t_e=np.zeros(n_rec)#array to be returned with time recorded for e_th event in all recvs
    t_e[0]=t_rec[0,e]
    for i in range(1,n_rec):#loop for rec
        d=sqrt((rec_pos[0,0]-rec_pos[i,0])**2+(rec_pos[0,1]-rec_pos[i,1])**2)
        t_expected=d/c,
        for j in range(0,n_events-1):
            if(abs(abs(t_rec[0,e]-t_rec[i,j])-t_expected)<\
               abs(abs(t_rec[0,e]-t_rec[i,j+1])-t_expected)):
                t_e[i]=t_rec[i,j]
            else: t_e[i]=t_rec[i,j+1]
    return t_e
          

In [5]:
t_1=arrange_events(1)
print(t_1)

[1.0050765  1.9803987  3.00311738]
